# Auto-generated by imp - DO NOT EDIT
# Regenerate with: nix run .#imp-flake

{
  description = "pw-tool: Playwright CLI in Rust";
  inputs = {
    # Core inputs
    flake-parts.url = "github:hercules-ci/flake-parts";
    imp.url = "github:imp-nix/imp-nix";
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    systems.url = "github:nix-systems/default";

    # Collected from __inputs
    rust-overlay.url = "github:oxalica/rust-overlay";
    rust-overlay.inputs.nixpkgs.follows = "nixpkgs";
    treefmt-nix.url = "github:numtide/treefmt-nix";
  };
  outputs = inputs: import ./nix/flake inputs;
}
